//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T_Veterinaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cita()
        {
            this.Detalle_Pago = new HashSet<Detalle_Pago>();
            this.Diagnostico = new HashSet<Diagnostico>();
        }
    
        public int CitaID { get; set; }
        public int MascotaID { get; set; }
        public int EmpleadoID { get; set; }
        public System.DateTime FechaCita { get; set; }
        public Nullable<int> ServicioID { get; set; }
        public int EstadoID { get; set; }
    
        public virtual Personal Personal { get; set; }
        public virtual Mascota Mascota { get; set; }
        public virtual Mascota Mascota1 { get; set; }
        public virtual Servicio Servicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Pago> Detalle_Pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diagnostico> Diagnostico { get; set; }
    }
}
